### ISSUE TITLE
adjustsFontSizeToFitWidth only works with numberOfLines = 1

### ISSUE THREAD

**Issue by codytwinton** [bteapot/BTLabel#1]
I'm trying to work with BTLabel to adjust the font size regardless of the `numberOfLines` property. There are times when 2 lines is necessary, but you still don't want the text truncated. How can this issue be addressed?

**Comment by bteapot** [comment]
Due to word wrapping, there is no way to make a good guess about font size that will suit requirements of fitting the specific text into specific number of lines. So the process of finding that font size will be potentially very resource-consuming: decreasing from given value by some delta, or bisection, then calling `boundingRectWithSize:options:context:`, comparing calculated height to current font's line height, further decreasing or bisecting font size, etc.

**Comment by codytwinton** [comment]
@bteapot - I was thinking something along this line. You pass the rect from `- (void)drawTextInRect:(CGRect)rect` to this method and it handles the font size for you:

```
- (void)setFontToFitFrame:(CGRect)rect
{
    CGFloat height = rect.size.height;

    if (self.font.lineHeight * self.numberOfLines > height) {
        while (self.font.lineHeight * self.numberOfLines > height) {
            self.font = [self.font fontWithSize:self.font.pointSize - 0.1];
        }
    }

    else {
        while (self.font.lineHeight * self.numberOfLines < height) {
            self.font = [self.font fontWithSize:self.font.pointSize + 0.1];
        }
        // went 1 point too large so compensate here
        self.font = [self.font fontWithSize:self.font.pointSize - 0.1];
    }
}
```

The rect is already set, so no need to call `boundingRectWithSize:options:context:`

**Comment by bteapot** [comment]
What about text width?
Lets say we have text `@"line-one\rline-two"` that will fit just fine into rect with width `100` and height `40` given font with `lineHeight == 20` and `numberOfLines == 2`.
What will happen if we replace `line-one` with `line-one-line-one-line-one-line-one-line-one-line-one-line-one-line-one-line-one-line-one-line-one-line-one-line-one-line-one-line-one-line-one`?

**Comment by codytwinton** [comment]
Well, if you're only allowing 2 lines, it doesn't matter if it's a line break via `\r` or via word wrapping. 2 lines is 2 lines.

**Comment by bteapot** [comment]
Ah, now I got the point.
Apple docs says that `A Boolean value indicating whether the font size should be reduced in order to fit the title string into the label’s bounding rectangle.` and `this property is effective only when the numberOfLines property is set to 1`. I don't want to break expecting behavior, so I need to add another flag here, different from `adjustsFontSizeToFitWidth`.
